version: '3.8'

services:
  api:
    build:           # dossier où se trouve le Dockerfile de ton API Python
    container_name: api-quests
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
      MYSQL_DB: quests_db
    ports:
      - "5000:5000"           # l'API est accessible sur http://localhost:5000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-quests
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quests_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql   # persistance des données MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-quests
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: user
      PMA_PASSWORD: userpass
    ports:
      - "8080:80"              # phpMyAdmin sur http://localhost:8080
    depends_on:
      - db

volumes:
  mysql_data:
